title: Site

# columns:
tabs:
  
  a_propos:
    icon: 🏛
    label: à Propos
    columns:
      - width: 1/1
          type: fields
          fields:
            apropos_text_content:
              label: Bubles texts
              type: blocks
              fieldsets:
                - text-bubble
      - width: 1/1
        type: fields
        fields:
          layouts:
            label: Images
            type: blocks
            fieldsets:
              - galerie-image
  restaurant:
    icon: 🥙
    label: Restaurant
    columns:
      - width: 1/1
          type: fields
          fields:
            restaurant_text_content:
              label: Bubles texts
              type: blocks
              fieldsets:
                - text-bubble
                
      - width: 1/1
          type: fields
          fields:
            rest_part_two:
              label: Horaire d'ouverture et prix
              type: writer
              width: 3/4
            rest_part_two_color: 
              label: couleur de texte
              type: radio
              options:
                - value: '#3C2109' 
                  text: '<div style="background-color: #3C2109; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFF4A' 
                  text: '<div style="background-color: #FFFF4A; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#005500' 
                  text: '<div style="background-color: #005500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#00B140' 
                  text: '<div style="background-color: #00B140; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FF4500' 
                  text: '<div style="background-color: #FF4500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#83CFFF' 
                  text: '<div style="background-color: #83CFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFD8E5' 
                  text: '<div style="background-color: #FFD8E5; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFFFF' 
                  text: '<div style="background-color: #FFFFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
              width: 1/4
      - width: 1/1
        type: fields
        fields:
          rest_galerie:
            label: Images
            type: blocks
            fieldsets:
              - galerie-image
  evenments:
    icon: 🎭
    label: évènements
    columns:
      - width: 1/1
          type: fields
          fields:
            event_text_content:
              label: Bubles texts
              type: blocks
              fieldsets:
                - text-bubble
      - width: 1/1
          type: fields
          fields:
            evnt_part_two:
              label: Tableau des évènements
              type: structure
              sortBy: date desc
              width: 1/1
              fields: 
                name:
                  label: Nom
                  type: text
                  width: 1/1
                date: 
                  label: Date
                  type: date
                  display: DD MMM YYYY
                  width: 1/4
                horaire:
                  label: Horaires
                  type: text
                  width: 1/4
                type:
                  label: Type
                  type: text
                  width: 1/4
                prix:
                  label: Prix
                  type: text 
                  width: 1/4  
            evnt_part_two_color:  
              label: couleur du texte
              type: radio
              options:
                - value: '#3C2109' 
                  text: '<div style="background-color: #3C2109; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFF4A' 
                  text: '<div style="background-color: #FFFF4A; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#005500' 
                  text: '<div style="background-color: #005500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#00B140' 
                  text: '<div style="background-color: #00B140; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FF4500' 
                  text: '<div style="background-color: #FF4500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#83CFFF' 
                  text: '<div style="background-color: #83CFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFD8E5' 
                  text: '<div style="background-color: #FFD8E5; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFFFF' 
                  text: '<div style="background-color: #FFFFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
              width: 1/2
            evnt_part_two_back:  
              label: couleur du back
              type: radio
              options:
                - value: '#3C2109' 
                  text: '<div style="background-color: #3C2109; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFF4A' 
                  text: '<div style="background-color: #FFFF4A; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#005500' 
                  text: '<div style="background-color: #005500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#00B140' 
                  text: '<div style="background-color: #00B140; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FF4500' 
                  text: '<div style="background-color: #FF4500; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#83CFFF' 
                  text: '<div style="background-color: #83CFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFD8E5' 
                  text: '<div style="background-color: #FFD8E5; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
                - value: '#FFFFFF' 
                  text: '<div style="background-color: #FFFFFF; border-radius: 10px; border: 1px solid #C3C3C3; height: 20px; margin-right: 10px;">'
              width: 1/2

      - width: 1/1
        type: fields
        fields:
          evnt_galerie:
            label: Images
            type: blocks
            fieldsets:
              - galerie-image  
  infos:
    icon: ☎️
    columns:
      - width: 1/1
          type: fields
          fields:
            contact_text_content:
              label: Bubles texts
              type: blocks
              fieldsets:
                - text-bubble
      - width: 1/1
          type: fields
          fields:
            contact_part_two:
              label: Emails de contact
              type: structure
              width: 1/2
              fields:
                label:
                  label: Label
                  type: text
                email:
                  label: Email
                  type: email
            contact_part_three:
              label: Texte
              type: writer
              width: 1/2
              nodes: false
              marks: 
                - link
                - email
  seo: 
    icon: text
    columns:
      - width: 1/1
          type: fields
          fields:
            title_site:
              label: Titre du site
              type: text
              width: 1/2
            base_site:
                label: Baseline du site
                type: text
                width: 1/2
            description_seo:
                label: Description du site pour SEO
                type: text
                width: 1/1
            gap10:
                type: gap
                width: 1/3
            image_seo:
                label: Image pour link SEO
                type: files
                width: 1/3

  gallery:
    label: "Gallery"
    icon: 🌆
    sections:
      images:
        headline: Website Images
        type: files
        # parent: site #this is optional, default is the current page  or the site
        layout: cards

